### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by Comarco** [millette/verra#20]
J'ai eu cette erreur et je n'ai pas eu la patience de voir si il uploaderait normalement après ça. J'ai killé et redemarré.

Juste pour noter.
```

{ Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }

```

**Comment by millette** [comment]
Bon, première fois que je watch pour de vrai, après 4-5 images j'ai aussi obtenu:

```
{ Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }
```

Et une seconde fois juste après l'avoir redémarré. Notons que verra semble continuer de fonctionner après cette erreur.
